# Generated by Django 4.0.4 on 2022-05-21 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0003_alter_event_options_event_status_event_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Todo',
        ),
    ]
