# Generated by Django 4.0.4 on 2022-05-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_rename_event_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='start_time',
            field=models.DateField(blank=True),
        ),
    ]
