# Generated by Django 4.0.4 on 2022-05-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_todo_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['completed']},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='status',
            new_name='completed',
        ),
    ]
