# Generated by Django 4.0.4 on 2022-07-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_payment_method_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_method',
            field=models.CharField(choices=[('IC', 'In cash'), ('IS', 'Installments'), ('EX', 'Exchange')], default='IC', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('PD', 'Payd'), ('PN', 'Pending'), ('CC', 'Cancelled')], default='PN', max_length=20),
        ),
    ]
