# Generated by Django 4.0.4 on 2023-10-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_payment_method_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_method',
            field=models.CharField(choices=[('AV', 'Á vista'), ('PC', 'Parcelado'), ('PM', 'Permuta')], default='AV', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('PG', 'Pago'), ('PN', 'Pendente'), ('CC', 'Cancelado')], default='PN', max_length=20),
        ),
    ]
