# Generated by Django 4.0.4 on 2023-10-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_payment_method_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('PD', 'Pago'), ('PN', 'Pendente'), ('CC', 'Cancelado')], default='PN', max_length=20),
        ),
    ]
