# Generated by Django 4.0.4 on 2022-05-30 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0006_clientdocuments_user_clientperson_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clausule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clausule_name', models.CharField(max_length=60)),
                ('clausule_type', models.CharField(max_length=60)),
                ('clausule_description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=90)),
                ('item_type', models.CharField(max_length=90)),
                ('item_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('item_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unity', models.CharField(choices=[('MT', 'Meters'), ('LT', 'Liters')], default='MT', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=60)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('installments', models.IntegerField(blank=True, null=True)),
                ('clausules', models.ManyToManyField(blank=True, null=True, to='contract_generator.clausule')),
                ('company_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.clientcompany')),
                ('items', models.ManyToManyField(blank=True, null=True, to='contract_generator.item')),
                ('person_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.clientperson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
