# Generated by Django 4.0.4 on 2022-05-30 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_value',
        ),
    ]
