# Generated by Django 4.0.4 on 2022-06-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('contract_generator', '0002_remove_item_item_quantity_remove_item_item_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontract',
            name='company_client',
        ),
        migrations.RemoveField(
            model_name='clientcontract',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientcontract',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='clientcontract',
            name='person_client',
        ),
        migrations.RemoveField(
            model_name='clientcontract',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='clientcontract',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='clientcontract',
            name='total_value',
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='original_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
    ]
