# Generated by Django 4.0.4 on 2022-06-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_generator', '0004_item_item_qt_item_item_total_item_item_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total',
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
