# Generated by Django 4.0.4 on 2022-06-21 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_generator', '0006_item_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_total',
        ),
    ]
