# Generated by Django 4.0.4 on 2022-06-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_generator', '0007_remove_item_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_total',
            field=models.FloatField(blank=True, max_length=12, null=True),
        ),
    ]
