# Generated by Django 4.0.4 on 2022-06-21 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_generator', '0008_item_item_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_total',
        ),
    ]
