# Generated by Django 4.0.4 on 2022-06-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_generator', '0009_remove_item_item_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('EQ', 'Equipment'), ('LB', 'Labor'), ('MR', 'Material')], default='MR', max_length=20),
        ),
    ]
