# Generated by Django 4.0.4 on 2022-06-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_generator', '0010_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unity',
            field=models.CharField(choices=[('MT', 'Meters'), ('LT', 'Liters'), ('NA', 'Na')], default='MT', max_length=20),
        ),
    ]
