# Generated by Django 4.0.4 on 2022-06-23 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_generator', '0011_alter_item_unity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientcontract',
            old_name='original_contract',
            new_name='work_order',
        ),
    ]
