# Generated by Django 4.0.4 on 2023-10-13 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_clientperson_cpf_alter_clientperson_first_name'),
        ('contract_generator', '0013_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='company_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.clientcompany'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Equipamento', 'Equipamento'), ('Mão de obra', 'Mão de obra'), ('Material', 'Material')], default='Material', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='unity',
            field=models.CharField(choices=[('MT', 'Metros'), ('LT', 'Litros'), ('-', '-')], default='MT', max_length=20),
        ),
    ]
