# Generated by Django 4.0.4 on 2022-05-10 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('company_cnpj', models.IntegerField(max_length=14)),
                ('phone', models.IntegerField(blank=True, max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pending_payments', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('received_payments', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=90)),
                ('cpf', models.IntegerField(max_length=11)),
                ('phone', models.IntegerField(blank=True, max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pending_payments', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('received_payments', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('person_company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='clients.clientcompany')),
            ],
        ),
    ]
