# Generated by Django 4.0.4 on 2022-05-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clientcompany_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcompany',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientperson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
