# Generated by Django 4.0.4 on 2022-05-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clientcompany_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('file_uploaded', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='clientperson',
            name='documents',
            field=models.ManyToManyField(blank=True, to='clients.clientdocuments'),
        ),
    ]
