# Generated by Django 4.0.4 on 2022-05-10 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientdocuments_clientperson_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdocuments',
            old_name='file_uploaded',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='clientperson',
            name='documents',
        ),
        migrations.AddField(
            model_name='clientdocuments',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.clientperson'),
        ),
    ]
