# Generated by Django 4.0.4 on 2022-05-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_rename_file_uploaded_clientdocuments_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdocuments',
            name='client',
        ),
        migrations.AddField(
            model_name='clientperson',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='clients.clientdocuments'),
        ),
    ]
