# Generated by Django 4.0.4 on 2022-05-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_clientdocuments_client_clientperson_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocuments',
            name='file',
            field=models.FileField(upload_to='clients_files'),
        ),
    ]
