# Generated by Django 4.0.4 on 2022-06-24 23:02

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_clientcompany_pending_payments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcompany',
            name='company_cnpj',
            field=django_cpf_cnpj.fields.CNPJField(max_length=18),
        ),
    ]
