# Generated by Django 4.0.4 on 2022-06-24 23:08

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_clientcompany_company_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientperson',
            name='first_name',
            field=django_cpf_cnpj.fields.CPFField(max_length=14),
        ),
    ]
