# Generated by Django 4.0.4 on 2022-06-24 23:10

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_clientperson_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientperson',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(max_length=14),
        ),
        migrations.AlterField(
            model_name='clientperson',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
    ]
