# Generated by Django 4.0.4 on 2022-05-12 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_clientcompany_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcompany',
            name='files',
        ),
        migrations.RemoveField(
            model_name='clientperson',
            name='files',
        ),
        migrations.AddField(
            model_name='clientdocuments',
            name='client_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.clientcompany'),
        ),
        migrations.AddField(
            model_name='clientdocuments',
            name='client_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.clientperson'),
        ),
    ]
