# Generated by Django 4.0.4 on 2023-10-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_clientperson_cpf_alter_clientperson_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientperson',
            old_name='first_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='clientperson',
            name='last_name',
        ),
    ]
